version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/ParcelRegistry.Api.CrabImport"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/ParcelRegistry.Api.Extract"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/ParcelRegistry.Api.Legacy"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/ParcelRegistry.Projections.Syndication"
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: "/src/ParcelRegistry.Projector"
  schedule:
    interval: daily
